#!/usr/bin/env bash
# Creates a Cloudflare Tunnel that fronts a bridge running on loopback, and
# writes the config `cloudflared` needs to run it as a service. This is the
# TLS + stable-hostname layer, not a compute host — see docs/HOSTING.md for
# why Cloudflare's own compute (Workers, Containers) isn't the right fit for
# an always-on process that spawns kiro-cli, and why Tunnel is the honest
# Cloudflare answer instead.
#
# WHERE TO RUN THIS: on the same host as the bridge. For the recommended
# all-cloud setup (docs/HOSTING.md "shape A") that host is the GCE VM from
# tools/deploy/gcp/ — SSH in and run it there, so cloudflared ends up running
# on the VM and nothing stays running on your own computer. Running it on
# your laptop next to a local bridge is the mixed shape C instead: same
# commands, $0/month, but reachable only while that laptop is awake.
#
# Run against a real account and a real zone on 2026-09-03. One bug surfaced
# immediately and is fixed below: the tunnel-ID lookup assumed compact JSON,
# and the failing grep took the whole script down under `set -euo pipefail`
# one line after a tunnel had actually been created. The rest of the path -
# login, create, route dns, config, systemd unit - is now verified end to end.
#
# The Cloudflare Access steps this script prints at the end, for the /qr pairing
# page, were followed for real on 2026-09-04: an application scoped to the /qr
# path with a Google policy, the two environment variables set on the VM, and a
# phone paired by scanning the page. /pair stayed reachable without an Access
# session throughout, which is the thing path-scoping exists to protect.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TUNNEL_NAME="${TUNNEL_NAME:-kiro-bridge}"
HOSTNAME="${HOSTNAME:-}"
BRIDGE_HOST="${BRIDGE_HOST:-localhost}"
BRIDGE_PORT="${KIRO_BRIDGE_PORT:-8765}"
CONFIG_DIR="${CONFIG_DIR:-$HOME/.cloudflared}"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared not found. Install it: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/" >&2
  exit 1
fi

if [ -z "$HOSTNAME" ]; then
  echo "Set HOSTNAME to the public hostname you want, e.g. bridge.example.com" >&2
  echo "It must be a hostname on a domain already added to your Cloudflare account" >&2
  echo "(the free plan is enough). Without a domain, see the 'quick tunnel'" >&2
  echo "fallback in tools/deploy/cloudflare/README.md instead of this script." >&2
  exit 1
fi

echo "==> cloudflared tunnel login"
echo "    Opens a browser against YOUR OWN Cloudflare account. One-time, per machine."
if [ ! -f "$CONFIG_DIR/cert.pem" ]; then
  cloudflared tunnel login
else
  echo "    already logged in ($CONFIG_DIR/cert.pem exists), skipping"
fi

echo "==> creating tunnel '$TUNNEL_NAME' (skips if it already exists)"
if ! cloudflared tunnel list --name "$TUNNEL_NAME" 2>/dev/null | grep -q "$TUNNEL_NAME"; then
  cloudflared tunnel create "$TUNNEL_NAME"
else
  echo "    tunnel '$TUNNEL_NAME' already exists, skipping create"
fi

# `tr -d` first: cloudflared pretty-prints its JSON, so the field arrives as
# `"id": "…"` with a space after the colon and the space-less pattern below
# matches nothing. That was not a cosmetic bug — under `set -euo pipefail` the
# failing grep killed this script silently, immediately after it had created a
# real tunnel, and the friendly error underneath was unreachable. `|| true`
# keeps that error reachable. Seen for real on 2026-09-03.
TUNNEL_ID="$(cloudflared tunnel list --name "$TUNNEL_NAME" -o json 2>/dev/null \
  | tr -d ' \n' | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4 || true)"
if [ -z "$TUNNEL_ID" ]; then
  echo "Could not resolve the tunnel ID for '$TUNNEL_NAME'. Run 'cloudflared tunnel list' and check by hand." >&2
  exit 1
fi
echo "    tunnel ID: $TUNNEL_ID"

echo "==> routing DNS: $HOSTNAME -> $TUNNEL_NAME"
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME"

CONFIG_FILE="$CONFIG_DIR/config.yml"
echo "==> writing $CONFIG_FILE"
cat > "$CONFIG_FILE" <<EOF
# Generated by tools/deploy/cloudflare/setup-tunnel.sh. Edit freely; re-running
# the script overwrites this file.
tunnel: $TUNNEL_ID
credentials-file: $CONFIG_DIR/$TUNNEL_ID.json

ingress:
  # http://, NOT ws://, and that distinction is load-bearing. Cloudflare proxies
  # a WebSocket upgrade transparently over an http(s) origin, so \`ws://\` buys
  # nothing — and it actively breaks the rest: with \`service: ws://…\` the edge
  # answers plain HTTP requests with **530** without ever reaching the origin.
  # The bridge serves plain HTTP routes too — \`POST /pair\`, and since F-30 also
  # \`GET /\` and \`GET /qr\` — so pairing failed with "the bridge refused the
  # pairing request" while the bridge logged nothing at all, because the request
  # never arrived. Verified on 2026-09-03: the WebSocket handshake succeeded
  # through a ws:// ingress and POST /pair returned 530; both work through http://.
  - hostname: $HOSTNAME
    service: http://$BRIDGE_HOST:$BRIDGE_PORT
  - service: http_status:404
EOF

cat <<EOF

==> Done. Tunnel '$TUNNEL_NAME' ($TUNNEL_ID) routes $HOSTNAME -> ws://$BRIDGE_HOST:$BRIDGE_PORT.

Run it two ways — pick one:

  1. systemd (see cloudflared.service in this directory — copy it to
     /etc/systemd/system/, adjust the config path if you changed CONFIG_DIR,
     then: sudo systemctl enable --now cloudflared)

  2. docker-compose, alongside the bridge container (see docker-compose.yml
     in this directory)

The bridge itself is unchanged by any of this: it still binds to loopback
and needs no TLS flags of its own — cloudflared is what terminates TLS, at
Cloudflare's edge, using the certificate for your domain, not the bridge's.

Point the app at: wss://$HOSTNAME/acp

ONE THING THE BRIDGE STILL NEEDS. It binds loopback and has no way to discover
the hostname you just created, so until you tell it, the QR in its pairing
banner carries ws://127.0.0.1:$BRIDGE_PORT/acp — which on a phone means the
phone. Tell it, and restart it once:

  echo 'KIRO_BRIDGE_PUBLIC_URL=wss://$HOSTNAME/acp' | sudo tee -a /etc/kiro-bridge.env
  sudo systemctl restart kiro-bridge

After that, pairing a phone never needs another restart:

  sudo runuser -u bridge -- /opt/kiro-bridge/bin/bridge pair \\
    --state-dir /home/bridge/.kiro-bridge

which prints a scannable QR of wss://$HOSTNAME/acp plus a fresh code.

PAIRING WITHOUT SSH AT ALL (optional). The bridge can serve the same QR as a web
page at https://$HOSTNAME/qr, behind Cloudflare Access, so a phone is added by
opening a URL and signing in with Google — no terminal anywhere. Two steps:

  1. In Zero Trust > Access > Applications, add a self-hosted application for
     **$HOSTNAME/qr** and give it a policy allowing your own email.

     *** SCOPE IT TO THE /qr PATH, NOT TO $HOSTNAME. ***
     The phone cannot complete a browser sign-in. An application covering the
     whole hostname breaks POST /pair and the /acp WebSocket, so the app stops
     pairing AND stops connecting — and its error will not point at Cloudflare.

  2. Copy the application's Application Audience (AUD) tag from its Overview
     tab, and your team domain from Zero Trust > Settings > General, then:

       echo 'KIRO_BRIDGE_ACCESS_TEAM_DOMAIN=<your-team>.cloudflareaccess.com' | sudo tee -a /etc/kiro-bridge.env
       echo 'KIRO_BRIDGE_ACCESS_AUD=<the AUD tag>' | sudo tee -a /etc/kiro-bridge.env
       sudo systemctl restart kiro-bridge

The bridge verifies that assertion itself — RS256 against your team's published
signing keys — rather than trusting the header, because its origin port is
reachable without going through this tunnel. Unconfigured, /qr answers 403 and
explains what is missing; it is opt-in and off by default.
EOF
