#!/usr/bin/env bash
# Creates a Cloudflare Tunnel that fronts a bridge running on loopback, and
# writes the config `cloudflared` needs to run it as a service. This is the
# TLS + stable-hostname layer, not a compute host — see docs/HOSTING.md for
# why Cloudflare's own compute (Workers, Containers) isn't the right fit for
# an always-on process that spawns kiro-cli, and why Tunnel is the honest
# Cloudflare answer instead.
#
# WHERE TO RUN THIS: on the same host as the bridge. For the recommended
# all-cloud setup (docs/HOSTING.md "shape A") that host is the GCE VM from
# tools/deploy/gcp/ — SSH in and run it there, so cloudflared ends up running
# on the VM and nothing stays running on your own computer. Running it on
# your laptop next to a local bridge is the mixed shape C instead: same
# commands, $0/month, but reachable only while that laptop is awake.
#
# NOT RUN AGAINST A REAL ACCOUNT while writing this: `cloudflared` happens to
# be installed on the machine that authored this script, which made it
# possible to check every flag below against real `--help` output, but
# `tunnel login`/`create`/`route dns` were never actually invoked. Read it
# before trusting it with a real domain.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TUNNEL_NAME="${TUNNEL_NAME:-kiro-bridge}"
HOSTNAME="${HOSTNAME:-}"
BRIDGE_HOST="${BRIDGE_HOST:-localhost}"
BRIDGE_PORT="${KIRO_BRIDGE_PORT:-8765}"
CONFIG_DIR="${CONFIG_DIR:-$HOME/.cloudflared}"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared not found. Install it: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/" >&2
  exit 1
fi

if [ -z "$HOSTNAME" ]; then
  echo "Set HOSTNAME to the public hostname you want, e.g. bridge.example.com" >&2
  echo "It must be a hostname on a domain already added to your Cloudflare account" >&2
  echo "(the free plan is enough). Without a domain, see the 'quick tunnel'" >&2
  echo "fallback in tools/deploy/cloudflare/README.md instead of this script." >&2
  exit 1
fi

echo "==> cloudflared tunnel login"
echo "    Opens a browser against YOUR OWN Cloudflare account. One-time, per machine."
if [ ! -f "$CONFIG_DIR/cert.pem" ]; then
  cloudflared tunnel login
else
  echo "    already logged in ($CONFIG_DIR/cert.pem exists), skipping"
fi

echo "==> creating tunnel '$TUNNEL_NAME' (skips if it already exists)"
if ! cloudflared tunnel list --name "$TUNNEL_NAME" 2>/dev/null | grep -q "$TUNNEL_NAME"; then
  cloudflared tunnel create "$TUNNEL_NAME"
else
  echo "    tunnel '$TUNNEL_NAME' already exists, skipping create"
fi

# `tr -d` first: cloudflared pretty-prints its JSON, so the field arrives as
# `"id": "…"` with a space after the colon and the space-less pattern below
# matches nothing. That was not a cosmetic bug — under `set -euo pipefail` the
# failing grep killed this script silently, immediately after it had created a
# real tunnel, and the friendly error underneath was unreachable. `|| true`
# keeps that error reachable. Seen for real on 2026-09-03.
TUNNEL_ID="$(cloudflared tunnel list --name "$TUNNEL_NAME" -o json 2>/dev/null \
  | tr -d ' \n' | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4 || true)"
if [ -z "$TUNNEL_ID" ]; then
  echo "Could not resolve the tunnel ID for '$TUNNEL_NAME'. Run 'cloudflared tunnel list' and check by hand." >&2
  exit 1
fi
echo "    tunnel ID: $TUNNEL_ID"

echo "==> routing DNS: $HOSTNAME -> $TUNNEL_NAME"
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME"

CONFIG_FILE="$CONFIG_DIR/config.yml"
echo "==> writing $CONFIG_FILE"
cat > "$CONFIG_FILE" <<EOF
# Generated by tools/deploy/cloudflare/setup-tunnel.sh. Edit freely; re-running
# the script overwrites this file.
tunnel: $TUNNEL_ID
credentials-file: $CONFIG_DIR/$TUNNEL_ID.json

ingress:
  # WebSocket is proxied transparently for an http(s)/ws(s) origin service —
  # no separate flag needed (Cloudflare has done this by default since 2022).
  - hostname: $HOSTNAME
    service: ws://$BRIDGE_HOST:$BRIDGE_PORT
  - service: http_status:404
EOF

cat <<EOF

==> Done. Tunnel '$TUNNEL_NAME' ($TUNNEL_ID) routes $HOSTNAME -> ws://$BRIDGE_HOST:$BRIDGE_PORT.

Run it two ways — pick one:

  1. systemd (see cloudflared.service in this directory — copy it to
     /etc/systemd/system/, adjust the config path if you changed CONFIG_DIR,
     then: sudo systemctl enable --now cloudflared)

  2. docker-compose, alongside the bridge container (see docker-compose.yml
     in this directory)

The bridge itself is unchanged by any of this: it still binds to loopback
and needs no TLS flags of its own — cloudflared is what terminates TLS, at
Cloudflare's edge, using the certificate for your domain, not the bridge's.

Point the app at: wss://$HOSTNAME/acp
EOF
